
export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇺🇸' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  { code: 'fr', name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '中文 (简体)', flag: '🇨🇳' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', flag: '🇰🇷' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', flag: '🇧🇷' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇧🇩' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', flag: '🇵🇰' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', flag: '🇹🇷' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', flag: '🇻🇳' },
];

export const getLanguageByCodeOrName = (val?: string): LanguageOption => {
  if (!val) return SUPPORTED_LANGUAGES[0];
  const lower = val.toLowerCase().trim();
  const match = SUPPORTED_LANGUAGES.find(
    l => l.name.toLowerCase() === lower || 
         l.code.toLowerCase() === lower || 
         l.nativeName.toLowerCase() === lower ||
         lower.includes(l.name.toLowerCase()) ||
         l.name.toLowerCase().includes(lower)
  );
  return match || { code: 'custom', name: val, nativeName: val, flag: '🌐' };
};

// UI string translations dictionary for core application views
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  // Navigation & Top Header
  'dashboard': {
    en: 'Dashboard',
    hi: 'डैशबोर्ड',
    es: 'Panel',
    fr: 'Tableau de bord',
    de: 'Dashboard',
    zh: '仪表板',
    ja: 'ダッシュボード',
    ko: '대시보드',
    ar: 'لوحة القيادة',
    pt: 'Painel',
    ru: 'Панель',
    it: 'Cruscotto',
    bn: 'ড্যাশবোর্ড',
    te: 'డాష్‌బోర్డ్',
    ta: 'முகப்பு பலகை',
    mr: 'डॅशबोर्ड',
    gu: 'ડેશબોર્ડ',
    kn: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    ml: 'ഡാഷ്‌ബോർഡ്',
    pa: 'ਡੈਸ਼ਬੋਰਡ',
    ur: 'ڈیش بورڈ',
    id: 'Dasbor',
    tr: 'Kontrol Paneli',
    vi: 'Bảng điều khiển',
  },
  'notes': {
    en: 'Smart Notes',
    hi: 'स्मार्ट नोट्स',
    es: 'Notas Inteligentes',
    fr: 'Notes Intelligentes',
    de: 'Smarte Notizen',
    zh: '智能笔记',
    ja: 'スマートノート',
    ko: '스마트 노트',
    ar: 'ملاحظات ذكية',
    pt: 'Notas Inteligentes',
    ru: 'Умные заметки',
    it: 'Note Intelligenti',
    bn: 'স্মার্ট নোট',
    te: 'స్మార్ట్ నోట్స్',
    ta: 'ஸ்மார்ட் குறிப்புகள்',
    mr: 'स्मार्ट नोट्स',
    gu: 'સ્માર્ટ નોટ્સ',
    kn: 'ಸ್ಮಾರ್ಟ್ ಟಿಪ್ಪಣಿಗಳು',
    ml: 'സ്മാർട്ട് കുറിപ്പുകൾ',
    pa: 'ਸਮਾਰਟ ਨੋਟਸ',
    ur: 'سمارٹ نوٹس',
    id: 'Catatan Pintar',
    tr: 'Akıllı Notlar',
    vi: 'Ghi chú thông minh',
  },
  'tutor_chat': {
    en: 'AI Tutor Chat',
    hi: 'एआई ट्यूटर चैट',
    es: 'Chat con Tutor IA',
    fr: 'Discussion avec Tuteur IA',
    de: 'KI-Tutor Chat',
    zh: 'AI 导师对话',
    ja: 'AIチューターチャット',
    ko: 'AI 튜터 채팅',
    ar: 'دردشة المعلم الذكي',
    pt: 'Chat com Tutor IA',
    ru: 'Чат с ИИ-репетитором',
    it: 'Chat con Tutor IA',
    bn: 'এআই টিউটর চ্যাট',
    te: 'AI ట్యూటర్ చాట్',
    ta: 'AI ஆசிரியர் அரட்டை',
    mr: 'AI शिक्षक चॅट',
    gu: 'AI શિક્ષક ચેટ',
    kn: 'AI ಶಿಕ್ಷಕ ಚಾಟ್',
    ml: 'AI ട്യൂട്ടർ ചാറ്റ്',
    pa: 'AI ਟਿਊਟਰ ਚੈਟ',
    ur: 'اے آئی ٹیوٹر چیٹ',
    id: 'Obrolan Tutor AI',
    tr: 'Yapay Zeka Eğitmen Sohbeti',
    vi: 'Trò chuyện cùng Gia sư AI',
  },
  'homework_solver': {
    en: 'Homework Solver',
    hi: 'होमवर्क सॉल्वर',
    es: 'Solucionador de Tareas',
    fr: 'Solveur de Devoirs',
    de: 'Hausaufgaben-Löser',
    zh: '作业解答器',
    ja: '宿題ソルバー',
    ko: '숙제 풀이 도우미',
    ar: 'حل الواجبات المنزلية',
    pt: 'Solucionador de Tarefas',
    ru: 'Помощник с домашним заданием',
    it: 'Risolutore di Compiti',
    bn: 'হোমওয়ার্ক সমাধানকারী',
    te: 'హోంవర్క్ సాల్వర్',
    ta: 'வீட்டுப்பாடம் தீர்க்கும் கருவி',
    mr: 'गृहपाठ सॉल्व्हर',
    gu: 'ગૃહકાર્ય ઉકેલનાર',
    kn: 'ಮನೆಕೆಲಸ ಪರಿಹಾರಕ',
    ml: 'ഹോംവർക്ക് സോൾവർ',
    pa: 'ਹੋਮਵਰਕ ਹੱਲ ਕਰਨ ਵਾਲਾ',
    ur: 'ہوم ورک حل کرنے والا',
    id: 'Pemecah PR',
    tr: 'Ödev Çözücü',
    vi: 'Giải bài tập về nhà',
  },
  'quiz_generator': {
    en: 'Quiz Generator',
    hi: 'क्विज जनरेटर',
    es: 'Generador de Cuestionarios',
    fr: 'Générateur de Quiz',
    de: 'Quiz-Generator',
    zh: '测验生成器',
    ja: 'クイズジェネレーター',
    ko: '퀴즈 생성기',
    ar: 'منشئ الاختبارات',
    pt: 'Gerador de Quiz',
    ru: 'Генератор тестов',
    it: 'Generatore di Quiz',
    bn: 'কুইজ জেনারেটর',
    te: 'క్విజ్ జనరేటర్',
    ta: 'வினாடி வினா உருவாக்கி',
    mr: 'क्विझ जनरेटर',
    gu: 'ક્વિઝ જનરેટર',
    kn: 'ರಸಪ್ರಶ್ನೆ ಜನರೇಟರ್',
    ml: 'ക്വിസ് ജനറേറ്റർ',
    pa: 'ਕਵਿਜ਼ ਜਨਰੇਟਰ',
    ur: 'کوئز جنریٹر',
    id: 'Pembuat Kuis',
    tr: 'Sınav Oluşturucu',
    vi: 'Tạo bài kiểm tra',
  },
  'timetable': {
    en: 'Study Timetable',
    hi: 'अध्ययन समय सारिणी',
    es: 'Horario de Estudio',
    fr: 'Emploi du temps d’étude',
    de: 'Studien-Stundenplan',
    zh: '学习时间表',
    ja: '学習時間割',
    ko: '학습 시간표',
    ar: 'جدول الدراسة',
    pt: 'Horário de Estudo',
    ru: 'Расписание занятий',
    it: 'Orario di Studio',
    bn: 'পড়ার সময়সূচী',
    te: 'స్టడీ టైమ్‌టేబుల్',
    ta: 'படிப்பு கால அட்டவணை',
    mr: 'अभ्यास वेळापत्रक',
    gu: 'અભ્યાસ સમયપત્રક',
    kn: 'ಅಧ್ಯಯನ ವೇಳಾಪಟ್ಟಿ',
    ml: 'പഠന ടൈംടേബിൾ',
    pa: 'ਅਧਿਐਨ ਟਾਈਮਟੇਬਲ',
    ur: 'مطالعہ کا ٹائم ٹیبل',
    id: 'Jadwal Belajar',
    tr: 'Çalışma Programı',
    vi: 'Thời khóa biểu học tập',
  },
  'settings': {
    en: 'Settings',
    hi: 'सेटिंग्स',
    es: 'Configuración',
    fr: 'Paramètres',
    de: 'Einstellungen',
    zh: '设置',
    ja: '設定',
    ko: '설정',
    ar: 'الإعدادات',
    pt: 'Configurações',
    ru: 'Настройки',
    it: 'Impostazioni',
    bn: 'সেটিংস',
    te: 'సెట్టింగ్‌లు',
    ta: 'அமைப்புகள்',
    mr: 'सेटिंग्ज',
    gu: 'સેટિંગ્સ',
    kn: 'ಸಂಯೋಜನೆಗಳು',
    ml: 'ക്രമീകരണങ്ങൾ',
    pa: 'ਸੈਟਿੰਗਾਂ',
    ur: 'ترتیبات',
    id: 'Pengaturan',
    tr: 'Ayarlar',
    vi: 'Cài đặt',
  },
  'profile': {
    en: 'Student Profile',
    hi: 'छात्र प्रोफ़ाइल',
    es: 'Perfil del Estudiante',
    fr: 'Profil Étudiant',
    de: 'Schülerprofil',
    zh: '学生档案',
    ja: '学生プロフィール',
    ko: '학생 프로필',
    ar: 'ملف الطالب',
    pt: 'Perfil do Estudante',
    ru: 'Профиль студента',
    it: 'Profilo Studente',
    bn: 'ছাত্র প্রোফাইল',
    te: 'విద్యార్థి ప్రొఫైల్',
    ta: 'மாணவர் சுயவிவரம்',
    mr: 'विद्यार्थी प्रोफाइल',
    gu: 'વિદ્યાર્થી પ્રોફાઇલ',
    kn: 'ವಿದ್ಯಾರ್ಥಿ ವಿವರ',
    ml: 'വിദ്യാർത്ഥി പ്രൊഫൈൽ',
    pa: 'ਵਿਦਿਆਰਥੀ ਪ੍ਰੋਫਾਈਲ',
    ur: 'طالب علم کا پروفائل',
    id: 'Profil Siswa',
    tr: 'Öğrenci Profili',
    vi: 'Hồ sơ học sinh',
  },
  'sign_in': {
    en: 'Sign In',
    hi: 'साइन इन करें',
    es: 'Iniciar sesión',
    fr: 'Se connecter',
    de: 'Anmelden',
    zh: '登录',
    ja: 'サインイン',
    ko: '로그인',
    ar: 'تسجيل الدخول',
    pt: 'Entrar',
    ru: 'Войти',
    it: 'Accedi',
    bn: 'সাইন ইন',
    te: 'సైన్ ఇన్',
    ta: 'உள்நுழைக',
    mr: 'साइन इन करा',
    gu: 'સાઇન ઇન કરો',
    kn: 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    ml: 'സൈൻ ഇൻ ചെയ്യുക',
    pa: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    ur: 'سائن ان کریں',
    id: 'Masuk',
    tr: 'Giriş Yap',
    vi: 'Đăng nhập',
  },
  'sign_up': {
    en: 'Sign Up / Register',
    hi: 'साइन अप / रजिस्टर',
    es: 'Registrarse',
    fr: 'S’inscrire',
    de: 'Registrieren',
    zh: '注册',
    ja: 'サインアップ / 登録',
    ko: '회원가입',
    ar: 'إنشاء حساب / تسجيل',
    pt: 'Inscrever-se',
    ru: 'Регистрация',
    it: 'Registrati',
    bn: 'নিবন্ধন করুন',
    te: 'నమోదు చేసుకోండి',
    ta: 'பதிவு செய்க',
    mr: 'नोंदणी करा',
    gu: 'નોંધણી કરો',
    kn: 'ನೋಂದಾಯಿಸಿ',
    ml: 'രജിസ്റ്റർ ചെയ്യുക',
    pa: 'ਰਜਿਸਟਰ ਕਰੋ',
    ur: 'رجسٹر کریں',
    id: 'Daftar',
    tr: 'Kayıt Ol',
    vi: 'Đăng ký',
  },
  'language': {
    en: 'Language',
    hi: 'भाषा',
    es: 'Idioma',
    fr: 'Langue',
    de: 'Sprache',
    zh: '语言',
    ja: '言語',
    ko: '언어',
    ar: 'اللغة',
    pt: 'Idioma',
    ru: 'Язык',
    it: 'Lingua',
    bn: 'ভাষা',
    te: 'భాష',
    ta: 'மொழி',
    mr: 'भाषा',
    gu: 'ભાષા',
    kn: 'ಭಾಷೆ',
    ml: 'ഭാഷ',
    pa: 'ਭਾਸ਼ਾ',
    ur: 'زبان',
    id: 'Bahasa',
    tr: 'Dil',
    vi: 'Ngôn ngữ',
  },
  'preferred_language': {
    en: 'Preferred Study Language',
    hi: 'पसंदीदा अध्ययन भाषा',
    es: 'Idioma preferido de estudio',
    fr: 'Langue d’étude préférée',
    de: 'Bevorzugte Lernsprache',
    zh: '首选学习语言',
    ja: '優先する学習言語',
    ko: '선호하는 학습 언어',
    ar: 'لغة الدراسة المفضلة',
    pt: 'Idioma de estudo preferido',
    ru: 'Предпочитаемый язык обучения',
    it: 'Lingua di studio preferita',
    bn: 'পছন্দের অধ্যয়নের ভাষা',
    te: 'ఇష్టపడే అధ్యయన భాష',
    ta: 'விருப்பமான படிப்பு மொழி',
    mr: 'पसंतीची अभ्यासाची भाषा',
    gu: 'પસંદગીની અભ્યાસ ભાષા',
    kn: 'ಆದ್ಯತೆಯ ಅಧ್ಯಯನ ಭಾಷೆ',
    ml: 'ഇഷ്ടപ്പെട്ട പഠന ഭാഷ',
    pa: 'ਪਸੰਦੀਦਾ ਅਧਿਐਨ ਭਾਸ਼ਾ',
    ur: 'پسندیدہ مطالعہ کی زبان',
    id: 'Bahasa Belajar Pilihan',
    tr: 'Tercih Edilen Çalışma Dili',
    vi: 'Ngôn ngữ học tập ưa thích',
  },
  'select_language_desc': {
    en: 'Select your preferred language for study notes, AI tutor chat, homework explanations, and study tools.',
    hi: 'अध्ययन नोट्स, एआई ट्यूटर चैट, होमवर्क व्याख्या और अध्ययन टूल के लिए अपनी पसंदीदा भाषा चुनें।',
    es: 'Seleccione su idioma preferido para notas de estudio, chat con tutor de IA, explicaciones de tareas y herramientas de estudio.',
    fr: 'Sélectionnez votre langue préférée pour les notes de cours, le chat avec le tuteur IA, les explications des devoirs et les outils d\'étude.',
    de: 'Wählen Sie Ihre bevorzugte Sprache für Lernnotizen, KI-Tutor-Chat, Hausaufgabenerklärungen und Lerntools.',
    zh: '为学习笔记、AI导师对话、作业解析和学习工具选择您的首选语言。',
    ja: '学習ノート、AIチューターチャット、宿題の解説、学習ツールで使用する優先言語を選択してください。',
    ko: '학습 노트, AI 튜터 채팅, 숙제 설명 및 학습 도구에 사용할 선호 언어를 선택하세요.',
    ar: 'اختر لغتك المفضلة لملاحظات الدراسة، ومحادثات المعلم الذكي، وشروحات الواجبات، وأدوات الدراسة.',
    pt: 'Selecione seu idioma preferido para anotações de estudo, chat com tutor de IA, explicações de tarefas e ferramentas de estudo.',
    ru: 'Выберите предпочитаемый язык для учебных заметок, чата с ИИ-репетитором, объяснения домашних заданий и учебных инструментов.',
    it: 'Seleziona la tua lingua preferita per le note di studio, la chat con il tutor IA, le spiegazioni dei compiti e gli strumenti di studio.',
    bn: 'অধ্যয়ন নোট, এআই টিউটর চ্যাট, বাড়ির কাজের ব্যাখ্যা এবং অধ্যয়নের সরঞ্জামের জন্য আপনার পছন্দের ভাষা নির্বাচন করুন।',
    te: 'స్టడీ నోట్స్, AI ట్యూటర్ చాట్, హోంవర్క్ వివరణలు మరియు స్టడీ టూల్స్ కోసం మీ ప్రాధాన్యత గల భాషను ఎంచుకోండి.',
    ta: 'படிப்பு குறிப்புகள், AI ஆசிரியர் அரட்டை, வீட்டுப்பாட விளக்கங்கள் மற்றும் படிப்பு கருவிகளுக்கான உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்.',
    mr: 'अभ्यास नोट्स, AI शिक्षक चॅट, गृहपाठ स्पष्टीकरण आणि अभ्यास साधनांसाठी तुमची पसंतीची भाषा निवडा.',
    gu: 'અભ્યાસ નોંધો, AI શિક્ષક ચેટ, ગૃહકાર્ય સમજૂતીઓ અને અભ્યાસ સાધનો માટે તમારી પસંદગીની ભાષા પસંદ કરો.',
    kn: 'ಅಧ್ಯಯನ ಟಿಪ್ಪಣಿಗಳು, AI ಶಿಕ್ಷಕರ ಚಾಟ್, ಮನೆಕೆಲಸ ವಿವರಣೆಗಳು ಮತ್ತು ಅಧ್ಯಯನ ಸಾಧನಗಳಿಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    ml: 'പഠന കുറിപ്പുകൾ, AI ട്യൂട്ടർ ചാറ്റ്, ഗൃഹപാഠ വിശദീകരണങ്ങൾ, പഠന ഉപകരണങ്ങൾ എന്നിവയ്ക്കായി നിങ്ങൾ ഇഷ്ടപ്പെടുന്ന ഭാഷ തിരഞ്ഞെടുക്കുക.',
    pa: 'ਅਧਿਐਨ ਨੋਟਸ, AI ਟਿਊਟਰ ਚੈਟ, ਹੋਮਵਰਕ ਵਿਆਖਿਆਵਾਂ ਅਤੇ ਅਧਿਐਨ ਸਾਧਨਾਂ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ।',
    ur: 'اسٹڈی نوٹس، اے آئی ٹیوٹر چیٹ، ہوم ورک کی وضاحتوں اور مطالعاتی ٹولز کے لیے اپنی پسندیدہ زبان منتخب کریں۔',
    id: 'Pilih bahasa pilihan Anda untuk catatan belajar, obrolan tutor AI, penjelasan PR, dan alat belajar.',
    tr: 'Çalışma notları, yapay zeka eğitmen sohbeti, ödev açıklamaları ve çalışma araçları için tercih ettiğiniz dili seçin.',
    vi: 'Chọn ngôn ngữ ưa thích của bạn cho ghi chú học tập, trò chuyện cùng gia sư AI, giải thích bài tập về nhà và công cụ học tập.',
  },
  'welcome_back': {
    en: 'Welcome Back 👋',
    hi: 'वापसी पर स्वागत है 👋',
    es: 'Bienvenido de nuevo 👋',
    fr: 'Content de vous revoir 👋',
    de: 'Willkommen zurück 👋',
    zh: '欢迎回来 👋',
    ja: 'おかえりなさい 👋',
    ko: '다시 오신 것을 환영합니다 👋',
    ar: 'مرحبًا بعودتك 👋',
    pt: 'Bem-vindo de volta 👋',
    ru: 'С возвращением 👋',
    it: 'Bentornato 👋',
    bn: 'আবার স্বাগতম 👋',
    te: 'తిరిగి స్వాగతం 👋',
    ta: 'மீண்டும் வருக 👋',
    mr: 'पुन्हा स्वागत आहे 👋',
    gu: 'પાછા સ્વાગત છે 👋',
    kn: 'ಮರಳಿ ಸುಸ್ವಾಗತ 👋',
    ml: 'വീണ്ടും സ്വാഗതം 👋',
    pa: 'ਜੀ ਆਇਆਂ ਨੂੰ 👋',
    ur: 'خوش آمدید 👋',
    id: 'Selamat Datang Kembali 👋',
    tr: 'Tekrar Hoş Geldiniz 👋',
    vi: 'Chào mừng trở lại 👋',
  },
  'create_account': {
    en: 'Create Your Account 🚀',
    hi: 'अपना खाता बनाएं 🚀',
    es: 'Crea tu cuenta 🚀',
    fr: 'Créez votre compte 🚀',
    de: 'Konto erstellen 🚀',
    zh: '创建您的账户 🚀',
    ja: 'アカウントを作成 🚀',
    ko: '계정 만들기 🚀',
    ar: 'أنشئ حسابك 🚀',
    pt: 'Crie sua conta 🚀',
    ru: 'Создать аккаунт 🚀',
    it: 'Crea il tuo account 🚀',
    bn: 'আপনার অ্যাকাউন্ট তৈরি করুন 🚀',
    te: 'మీ ఖాతాను సృష్టించండి 🚀',
    ta: 'உங்கள் கணக்கை உருவாக்கவும் 🚀',
    mr: 'तुमचे खाते तयार करा 🚀',
    gu: 'તમારું એકાઉન્ટ બનાવો 🚀',
    kn: 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ರಚಿಸಿ 🚀',
    ml: 'നിങ്ങളുടെ അക്കൗണ്ട് സൃഷ്ടിക്കുക 🚀',
    pa: 'ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ 🚀',
    ur: 'اپنا اکاؤنٹ بنائیں 🚀',
    id: 'Buat Akun Anda 🚀',
    tr: 'Hesabınızı Oluşturun 🚀',
    vi: 'Tạo tài khoản của bạn 🚀',
  },
  'join_subtext': {
    en: 'Join SJ Tutor AI and start learning today.',
    hi: 'SJ Tutor AI से जुड़ें और आज ही सीखना शुरू करें।',
    es: 'Únete a SJ Tutor AI y comienza a aprender hoy.',
    fr: 'Rejoignez SJ Tutor AI et commencez à apprendre dès aujourd\'hui.',
    de: 'Treten Sie SJ Tutor AI bei und beginnen Sie noch heute mit dem Lernen.',
    zh: '加入 SJ Tutor AI，立即开始学习。',
    ja: 'SJ Tutor AI に参加して、今日から学習を始めましょう。',
    ko: 'SJ Tutor AI에 가입하고 오늘 바로 학습을 시작하세요.',
    ar: 'انضم إلى SJ Tutor AI وابدأ التعلم اليوم.',
    pt: 'Junte-se ao SJ Tutor AI e comece a aprender hoje mesmo.',
    ru: 'Присоединяйтесь к SJ Tutor AI и начните учиться уже сегодня.',
    it: 'Unisciti a SJ Tutor AI e inizia a imparare oggi.',
    bn: 'SJ Tutor AI-তে যোগ দিন এবং আজই শেখা শুরু করুন।',
    te: 'SJ Tutor AI లో చేరండి మరియు ఈరోజే నేర్చుకోవడం ప్రారంభించండి.',
    ta: 'SJ Tutor AI இல் சேர்ந்து இன்றே கற்கத் தொடங்குங்கள்.',
    mr: 'SJ Tutor AI मध्ये सामील व्हा आणि आजच शिकणे सुरू करा.',
    gu: 'SJ Tutor AI માં જોડાઓ અને આજથી જ શીખવાનું શરૂ કરો.',
    kn: 'SJ Tutor AI ಗೆ ಸೇರಿ ಮತ್ತು ಇಂದೇ ಕಲಿಯಲು ಪ್ರಾರಂಭಿಸಿ.',
    ml: 'SJ Tutor AI-ൽ ചേരൂ, ഇന്ന് തന്നെ പഠനം ആരംഭിക്കൂ.',
    pa: 'SJ Tutor AI ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ ਅਤੇ ਅੱਜ ਹੀ ਸਿੱਖਣਾ ਸ਼ੁਰੂ ਕਰੋ।',
    ur: 'SJ Tutor AI میں شامل ہوں اور آج ہی سیکھنا شروع کریں۔',
    id: 'Bergabunglah dengan SJ Tutor AI dan mulailah belajar hari ini.',
    tr: 'SJ Tutor AI\'ya katılın ve bugün öğrenmeye başlayın.',
    vi: 'Tham gia SJ Tutor AI và bắt đầu học ngay hôm nay.',
  },
  'full_name': {
    en: 'Full Name',
    hi: 'पूरा नाम',
    es: 'Nombre completo',
    fr: 'Nom complet',
    de: 'Vollständiger Name',
    zh: '全名',
    ja: '氏名',
    ko: '이름',
    ar: 'الاسم الكامل',
    pt: 'Nome Completo',
    ru: 'Полное имя',
    it: 'Nome completo',
    bn: 'পুরো নাম',
    te: 'పూర్తి పేరు',
    ta: 'முழு பெயர்',
    mr: 'पूर्ण नाव',
    gu: 'પૂરું નામ',
    kn: 'ಪೂರ್ಣ ಹೆಸರು',
    ml: 'പൂർണ്ണ പേര്',
    pa: 'ਪੂਰਾ ਨਾਮ',
    ur: 'پورا نام',
    id: 'Nama Lengkap',
    tr: 'Tam Ad',
    vi: 'Họ và tên',
  },
  'email_address': {
    en: 'Email Address',
    hi: 'ईमेल पता',
    es: 'Correo electrónico',
    fr: 'Adresse e-mail',
    de: 'E-Mail-Adresse',
    zh: '电子邮件地址',
    ja: 'メールアドレス',
    ko: '이메일 주소',
    ar: 'البريد الإلكتروني',
    pt: 'Endereço de e-mail',
    ru: 'Адрес электронной почты',
    it: 'Indirizzo e-mail',
    bn: 'ইমেল ঠিকানা',
    te: 'ఇమెయిల్ చిరునామా',
    ta: 'மின்னஞ்சல் முகவரி',
    mr: 'ईमेल पत्ता',
    gu: 'ઈમેલ સરનામું',
    kn: 'ಇಮೇಲ್ ವಿಳಾಸ',
    ml: 'ഇമെയിൽ വിലാസം',
    pa: 'ਈਮੇਲ ਪਤਾ',
    ur: 'ای میل ایڈریس',
    id: 'Alamat Email',
    tr: 'E-posta Adresi',
    vi: 'Địa chỉ Email',
  },
  'password': {
    en: 'Password',
    hi: 'पासवर्ड',
    es: 'Contraseña',
    fr: 'Mot de passe',
    de: 'Passwort',
    zh: '密码',
    ja: 'パスワード',
    ko: '비밀번호',
    ar: 'كلمة المرور',
    pt: 'Senha',
    ru: 'Пароль',
    it: 'Password',
    bn: 'পাসওয়ার্ড',
    te: 'పాస్‌వర్డ్',
    ta: 'கடவுச்சொல்',
    mr: 'पासवर्ड',
    gu: 'પાસવર્ડ',
    kn: 'ಪಾಸ್‌ವರ್ಡ್',
    ml: 'പാസ്‌വേഡ്',
    pa: 'ਪਾਸਵਰਡ',
    ur: 'پاس ورڈ',
    id: 'Kata Sandi',
    tr: 'Şifre',
    vi: 'Mật khẩu',
  },
  'continue_with_google': {
    en: 'Continue with Google',
    hi: 'Google के साथ जारी रखें',
    es: 'Continuar con Google',
    fr: 'Continuer avec Google',
    de: 'Mit Google fortfahren',
    zh: '通过 Google 继续',
    ja: 'Google で続行',
    ko: 'Google로 계속하기',
    ar: 'المتابعة باستخدام Google',
    pt: 'Continuar com o Google',
    ru: 'Продолжить с Google',
    it: 'Continua con Google',
    bn: 'Google দিয়ে চালিয়ে যান',
    te: 'Google తో కొనసాగండి',
    ta: 'Google மூலம் தொடரவும்',
    mr: 'Google सह सुरू ठेवा',
    gu: 'Google સાથે ચાલુ રાખો',
    kn: 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    ml: 'Google ഉപയോഗിച്ച് തുടരുക',
    pa: 'Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ',
    ur: 'Google کے ساتھ جاری رکھیں',
    id: 'Lanjutkan dengan Google',
    tr: 'Google ile Devam Et',
    vi: 'Tiếp tục với Google',
  },
  'signup_with_google': {
    en: 'Sign Up with Google',
    hi: 'Google के साथ साइन अप करें',
    es: 'Registrarse con Google',
    fr: 'S\'inscrire avec Google',
    de: 'Mit Google registrieren',
    zh: '通过 Google 注册',
    ja: 'Google で登録',
    ko: 'Google로 가입하기',
    ar: 'التسجيل باستخدام Google',
    pt: 'Inscrever-se com o Google',
    ru: 'Зарегистрироваться с Google',
    it: 'Registrati con Google',
    bn: 'Google দিয়ে নিবন্ধন করুন',
    te: 'Google తో సైన్ అప్ చేయండి',
    ta: 'Google மூலம் பதிவு செய்க',
    mr: 'Google सह साइन अप करा',
    gu: 'Google સાથે સાઇન અપ કરો',
    kn: 'Google ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    ml: 'Google ഉപയോഗിച്ച് സൈൻ അപ്പ് ചെയ്യുക',
    pa: 'Google ਨਾਲ ਸਾਈਨ ਅੱਪ ਕਰੋ',
    ur: 'Google کے ساتھ سائن اپ کریں',
    id: 'Daftar dengan Google',
    tr: 'Google ile Kayıt Ol',
    vi: 'Đăng ký với Google',
  },
  'save_changes': {
    en: 'Save Changes',
    hi: 'बदलाव सहेजें',
    es: 'Guardar cambios',
    fr: 'Enregistrer les modifications',
    de: 'Änderungen speichern',
    zh: '保存更改',
    ja: '変更を保存',
    ko: '변경 사항 저장',
    ar: 'حفظ التغييرات',
    pt: 'Salvar alterações',
    ru: 'Сохранить изменения',
    it: 'Salva modifiche',
    bn: 'পরিবর্তন সংরক্ষণ করুন',
    te: 'మార్పులను సేవ్ చేయండి',
    ta: 'மாற்றங்களைச் சேமிக்கவும்',
    mr: 'बदल जतन करा',
    gu: 'ફેરફારો સાચવો',
    kn: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    ml: 'മാറ്റങ്ങൾ സംരക്ഷിക്കുക',
    pa: 'ਤਬਦੀਲੀਆਂ ਸੁਰੱਖਿਅਤ ਕਰੋ',
    ur: 'تبدیلیاں محفوظ کریں',
    id: 'Simpan Perubahan',
    tr: 'Değişiklikleri Kaydet',
    vi: 'Lưu thay đổi',
  },
};

export const t = (key: string, languageNameOrCode?: string): string => {
  const lang = getLanguageByCodeOrName(languageNameOrCode || 'English');
  const code = lang.code;
  const dict = TRANSLATIONS[key];
  if (!dict) return key;
  return dict[code] || dict['en'] || key;
};
