
import React, { useState, useEffect } from 'react';
import { QuizQuestion, SJTUTOR_AVATAR } from '../types';
import { CheckCircle, XCircle, ArrowRight, RefreshCw, Facebook, Send, MessageCircle, Link, Share2, X, Trophy } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface QuizViewProps {
  questions: QuizQuestion[];
  onReset: () => void;
  onComplete?: (score: number) => void;
  existingScore?: number;
  userId?: string;
}

const QuizView: React.FC<QuizViewProps> = ({ questions, onReset, onComplete, existingScore, userId }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [quizCompleted, setQuizCompleted] = useState(false);
  const [showResultModal, setShowResultModal] = useState(false);

  // Persistence Key - unique per set of questions and user
  const persistenceKey = `sj_quiz_progress_${userId || 'guest'}_${questions[0]?.question.substring(0, 20)}`;

  // Load persistence
  useEffect(() => {
    if (existingScore === undefined) {
      const saved = localStorage.getItem(persistenceKey);
      if (saved) {
        try {
          const { index, currentScore, isCompleted } = JSON.parse(saved);
          if (!isCompleted) {
            setCurrentIndex(index);
            setScore(currentScore);
          }
        } catch (e) {
          console.error("Failed to load quiz progress", e);
        }
      }
    }
  }, [persistenceKey, existingScore]);

  // Save persistence
  useEffect(() => {
    if (existingScore === undefined && !quizCompleted && questions.length > 0) {
      localStorage.setItem(persistenceKey, JSON.stringify({
        index: currentIndex,
        currentScore: score,
        isCompleted: false
      }));
    }
  }, [currentIndex, score, quizCompleted, persistenceKey, existingScore, questions]);

  // Clear persistence on completion
  useEffect(() => {
    if (quizCompleted) {
      localStorage.removeItem(persistenceKey);
    }
  }, [quizCompleted, persistenceKey]);

  // Initialize view if there's an existing score (viewing history)
  useEffect(() => {
    if (existingScore !== undefined) {
      setScore(existingScore);
      setQuizCompleted(true);
      setShowResultModal(true);
    } else {
      // Reset state for new quiz
      setCurrentIndex(0);
      setScore(0);
      setQuizCompleted(false);
      setShowResult(false);
      setSelectedOption(null);
      setShowResultModal(false);
    }
  }, [existingScore, questions]);

  const currentQuestion = questions[currentIndex];

  const handleOptionSelect = (index: number) => {
    if (showResult) return;
    setSelectedOption(index);
    setShowResult(true);
    if (index === currentQuestion.correctAnswerIndex) {
      setScore(s => s + 1);
    }
  };

  const handleNext = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(prev => prev + 1);
      setSelectedOption(null);
      setShowResult(false);
    } else {
      setQuizCompleted(true);
      setShowResultModal(true);
      if (onComplete) {
        onComplete(score);
      }
    }
  };

  const handleShareQuizContent = async () => {
     // Format quiz into text
     let text = "🧠 SJ Tutor AI Quiz Challenge 🧠\n\n";
     questions.forEach((q, i) => {
         text += `Q${i+1}: ${q.question}\n`;
         q.options.forEach((opt, j) => {
             text += `   ${String.fromCharCode(65+j)}) ${opt}\n`;
         });
         text += "\n";
     });
     text += "\nCan you beat my score? Generated by SJ Tutor AI.";

    if (navigator.share) {
        try {
            await navigator.share({
                title: 'SJ Tutor AI Quiz Challenge',
                text: text
            });
        } catch (e) { console.log('Share canceled'); }
    } else {
        try {
            await navigator.clipboard.writeText(text);
            alert('Quiz questions copied to clipboard!');
        } catch (e) { alert('Failed to copy'); }
    }
  };

  const handleShare = async (platform: string) => {
    try {
      // 1. Save to backend to get a unique public ID
      const response = await fetch('/api/auth/share', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'QUIZ',
          title: 'Quiz Challenge',
          subtitle: `I scored ${score}/${questions.length} on this quiz!`,
          content: questions
        })
      });

      if (!response.ok) {
        throw new Error(`Server returned ${response.status}`);
      }

      const contentType = response.headers.get("content-type");
      if (!contentType || !contentType.includes("application/json")) {
        throw new Error("Invalid response from server");
      }

      const data = await response.json();
      const shareId = data.id;
      const shareUrl = `${window.location.origin}?share=${shareId}`;
      const text = `I scored ${score}/${questions.length} on my SJ Tutor AI Quiz! 🎓`;
      const shareTextWithLink = `${text}\nCheck it out here: ${shareUrl}`;
      
      let url = '';
      switch(platform) {
        case 'whatsapp':
          url = `https://wa.me/?text=${encodeURIComponent(shareTextWithLink)}`;
          break;
        case 'facebook':
          url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(text)}`;
          break;
        case 'telegram':
            url = `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(text)}`;
            break;
        case 'gmail':
             url = `https://mail.google.com/mail/u/0/?view=cm&fs=1&su=${encodeURIComponent("My SJ Tutor AI Score")}&body=${encodeURIComponent(shareTextWithLink)}`;
             break;
        case 'email':
          url = `mailto:?subject=My SJ Tutor AI Score&body=${encodeURIComponent(shareTextWithLink)}`;
          break;
        case 'instagram':
            navigator.clipboard.writeText(shareTextWithLink);
            alert("Score and link copied! Open Instagram to paste and share.");
            url = 'https://instagram.com';
            break;
                case 'copy':
                    if (navigator.share) {
                      try {
                        await navigator.share({
                          title: 'My SJ Tutor AI Score',
                          text: text,
                          url: shareUrl,
                        });
                        return;
                      } catch (err) {
                        console.debug("Native share canceled or failed", err);
                      }
                    }
            navigator.clipboard.writeText(shareUrl);
            alert("Share link copied to clipboard!");
            return;
      }
      
      if (url) window.open(url, '_blank');
    } catch (err: any) {
      console.error(err);
      alert('Sharing failed: ' + err.message);
    }
  };

  const renderResultModal = () => {
    const percentage = Math.round((score / questions.length) * 100);
    let message = "Good effort!";
    if (percentage >= 80) message = "Excellent work!";
    else if (percentage >= 50) message = "Keep practicing!";

    return (
      <AnimatePresence>
        {showResultModal && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-sm">
            <motion.div 
              initial={{ opacity: 0, scale: 0.9, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.9, y: 20 }}
              className="bg-white dark:bg-slate-900 rounded-3xl shadow-2xl overflow-hidden max-w-lg w-full relative border border-white/10"
            >
              <button 
                onClick={() => setShowResultModal(false)}
                className="absolute top-4 right-4 p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors z-20 text-slate-400"
              >
                <X className="w-5 h-5" />
              </button>

              <div className="p-8 text-center">
                <div className="w-24 h-24 bg-gradient-to-br from-primary-400 to-primary-600 rounded-full flex items-center justify-center mx-auto mb-6 shadow-xl relative">
                   <Trophy className="w-12 h-12 text-white" />
                   <motion.div 
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ delay: 0.3, type: 'spring' }}
                    className="absolute -right-2 -bottom-2 bg-emerald-500 text-white p-2 rounded-full border-4 border-white dark:border-slate-900"
                   >
                    <CheckCircle className="w-6 h-6" />
                   </motion.div>
                </div>

                <h2 className="text-3xl font-black text-slate-900 dark:text-white mb-2 tracking-tight">
                  Quiz Completed!
                </h2>
                <p className="text-slate-500 dark:text-slate-400 mb-8 font-medium italic">&quot;{message}&quot;</p>
                
                <div className="bg-slate-50 dark:bg-slate-800/50 rounded-2xl p-6 mb-8 border border-slate-100 dark:border-slate-800">
                  <div className="text-6xl font-black text-primary-600 mb-1 tracking-tighter">
                    {score}<span className="text-2xl text-slate-300 dark:text-slate-600 font-normal">/{questions.length}</span>
                  </div>
                  <p className="text-xs text-slate-400 dark:text-slate-500 uppercase tracking-widest font-bold">Your Score</p>
                </div>

                <div className="grid grid-cols-2 gap-4 mb-8">
                  <button
                      onClick={onReset}
                      className="flex items-center justify-center px-6 py-4 bg-primary-600 hover:bg-primary-700 text-white rounded-xl font-bold transition-all shadow-lg shadow-primary-600/20 active:scale-95"
                  >
                      <RefreshCw className="w-4 h-4 mr-2" />
                      Retake
                  </button>
                  <button
                      onClick={handleShareQuizContent}
                      className="flex items-center justify-center px-6 py-4 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700 rounded-xl font-bold transition-all active:scale-95 shadow-sm"
                  >
                      <Share2 className="w-4 h-4 mr-2" />
                      Share
                  </button>
                </div>

                <div className="border-t border-slate-100 dark:border-slate-800 pt-6">
                  <p className="text-[10px] font-black text-slate-400 dark:text-slate-600 uppercase tracking-[0.2em] mb-4">Quick Share Score</p>
                  <div className="flex justify-center gap-3">
                      {['whatsapp', 'facebook', 'telegram', 'copy'].map(plat => (
                        <button 
                          key={plat}
                          onClick={() => handleShare(plat)} 
                          className="p-3 bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 rounded-full hover:bg-primary-50 dark:hover:bg-primary-900/30 hover:text-primary-600 transition-all hover:scale-110"
                        >
                          {plat === 'whatsapp' && <MessageCircle className="w-5 h-5" />}
                          {plat === 'facebook' && <Facebook className="w-5 h-5" />}
                          {plat === 'telegram' && <Send className="w-5 h-5" />}
                          {plat === 'copy' && <Link className="w-5 h-5" />}
                        </button>
                      ))}
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    );
  };

  return (
    <div className="space-y-6">
      {renderResultModal()}
      
      {quizCompleted && (
        <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-md border border-slate-200 dark:border-slate-800 overflow-hidden animate-in slide-in-from-bottom-4 duration-500">
            <div className="px-6 py-4 bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800 flex justify-between items-center">
                <h3 className="font-bold text-slate-800 dark:text-white flex items-center gap-2 text-lg">
                    <CheckCircle className="w-5 h-5 text-emerald-500" />
                    Review Answers
                </h3>
                <button 
                  onClick={() => setShowResultModal(true)}
                  className="text-primary-600 font-bold text-sm hover:underline"
                >
                  View Final Score
                </button>
            </div>
            <div className="divide-y divide-slate-100 dark:divide-slate-800">
                {questions.map((q, idx) => (
                    <div key={idx} className="p-6">
                        <p className="font-semibold text-slate-800 dark:text-slate-200 mb-4 flex gap-3">
                            <span className="text-slate-400 font-mono bg-slate-100 dark:bg-slate-800 px-2 py-0.5 rounded text-sm">{idx + 1}</span>
                            {q.question}
                        </p>
                        <div className="space-y-2 pl-8 mb-4">
                            {q.options.map((opt, optIdx) => (
                                <div 
                                    key={optIdx} 
                                    className={`px-4 py-3 rounded-xl border text-sm flex justify-between items-center transition-all ${
                                        optIdx === q.correctAnswerIndex 
                                        ? 'bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800 text-emerald-800 dark:text-emerald-300 font-bold' 
                                        : 'bg-white dark:bg-slate-900 border-slate-100 dark:border-slate-800 text-slate-500 dark:text-slate-400'
                                    }`}
                                >
                                    <span>{opt}</span>
                                    {optIdx === q.correctAnswerIndex && <CheckCircle className="w-4 h-4 text-emerald-500" />}
                                </div>
                            ))}
                        </div>
                        <div className="ml-8 p-4 bg-slate-50 dark:bg-slate-800/30 rounded-xl text-sm text-slate-600 dark:text-slate-400 border border-slate-100 dark:border-slate-800 italic">
                            <span className="font-bold text-slate-700 dark:text-slate-300 not-italic">Quick Tip: </span>
                            {q.explanation}
                        </div>
                    </div>
                ))}
            </div>
            <div className="p-6 bg-slate-50 dark:bg-slate-800/50 border-t border-slate-200 dark:border-slate-800 text-center">
               <button
                  onClick={onReset}
                  className="px-8 py-3 bg-primary-600 text-white rounded-xl font-bold shadow-lg shadow-primary-600/20 hover:scale-105 active:scale-95 transition-all"
                >
                  Ready for another challenge?
                </button>
            </div>
        </div>
      )}

      <div className={`bg-white dark:bg-slate-900 rounded-2xl shadow-xl border border-slate-200 dark:border-slate-800 overflow-hidden ${quizCompleted ? 'hidden' : 'block'}`}>
        {/* Progress Bar */}
        <div className="w-full bg-slate-100 h-1.5">
          <div 
            className="bg-primary-600 h-1.5 transition-all duration-300"
            style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }}
          ></div>
        </div>

        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <span className="text-xs font-bold text-primary-600 uppercase tracking-wider bg-primary-50 px-2 py-1 rounded">
              Question {currentIndex + 1} of {questions.length}
            </span>
            <span className="text-sm font-medium text-slate-500">Score: {score}</span>
          </div>

          <h3 className="text-xl font-semibold text-slate-800 mb-6">
            {currentQuestion.question}
          </h3>

          <div className="space-y-3">
            {currentQuestion.options.map((option, idx) => {
              let optionClass = "border-slate-200 hover:border-primary-300 hover:bg-slate-50";
              let icon = null;

              if (showResult) {
                if (idx === currentQuestion.correctAnswerIndex) {
                  optionClass = "border-emerald-500 bg-emerald-50 text-emerald-800 ring-1 ring-emerald-500";
                  icon = <CheckCircle className="w-5 h-5 text-emerald-600" />;
                } else if (idx === selectedOption) {
                  optionClass = "border-rose-500 bg-rose-50 text-rose-800 ring-1 ring-rose-500";
                  icon = <XCircle className="w-5 h-5 text-rose-600" />;
                } else {
                  optionClass = "border-slate-100 opacity-50";
                }
              } else if (selectedOption === idx) {
                 optionClass = "border-primary-500 bg-primary-50 ring-1 ring-primary-500";
              }

              return (
                <button
                  key={idx}
                  onClick={() => handleOptionSelect(idx)}
                  disabled={showResult}
                  className={`w-full text-left p-4 rounded-lg border-2 transition-all flex justify-between items-center ${optionClass}`}
                >
                  <span className="font-medium">{option}</span>
                  {icon}
                </button>
              );
            })}
          </div>

          {showResult && (
            <div className="mt-6 animate-in fade-in slide-in-from-top-2">
              <div className="bg-slate-50 p-4 rounded-lg border border-slate-200 mb-6">
                <span className="block text-xs font-bold text-slate-500 uppercase mb-1">Explanation</span>
                <p className="text-slate-700">{currentQuestion.explanation}</p>
              </div>
              <div className="flex justify-end">
                <button
                  onClick={handleNext}
                  className="inline-flex items-center px-6 py-2.5 bg-primary-600 hover:bg-primary-700 text-white rounded-lg font-medium transition-colors shadow-lg shadow-primary-500/20"
                >
                  {currentIndex === questions.length - 1 ? 'Finish Quiz' : 'Next Question'}
                  <ArrowRight className="w-4 h-4 ml-2" />
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default QuizView;
