
import React, { useState, useEffect } from 'react';
import { QuizQuestion, SJTUTOR_AVATAR, UserProfile } from '../types';
import { CheckCircle, XCircle, ArrowRight, RefreshCw, Facebook, Instagram, Mail, Send, MessageCircle, Link, Share2, Trophy, Award, Coins } from 'lucide-react';
import confetti from 'canvas-confetti';
import { motion, AnimatePresence } from 'motion/react';

interface QuizViewProps {
  questions: QuizQuestion[];
  onReset: () => void;
  onComplete?: (score: number, pointsEarned: number) => void;
  existingScore?: number;
  userProfile: UserProfile;
}

const QuizView: React.FC<QuizViewProps> = ({ questions, onReset, onComplete, existingScore }) => {
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedOption, setSelectedOption] = useState<number | null>(null);
  const [score, setScore] = useState(0);
  const [showResult, setShowResult] = useState(false);
  const [quizCompleted, setQuizCompleted] = useState(false);

  // Initialize view if there's an existing score (viewing history)
  useEffect(() => {
    if (existingScore !== undefined) {
      setScore(existingScore);
      setQuizCompleted(true);
    } else {
      // Reset state for new quiz
      setCurrentIndex(0);
      setScore(0);
      setQuizCompleted(false);
      setShowResult(false);
      setSelectedOption(null);
    }
  }, [existingScore, questions]);

  const currentQuestion = questions[currentIndex];

  const triggerConfetti = () => {
    const end = Date.now() + 3 * 1000;
    const colors = ['#D4AF37', '#B7950B', '#3b82f6', '#10b981'];

    (function frame() {
      confetti({
        particleCount: 3,
        angle: 60,
        spread: 55,
        origin: { x: 0 },
        colors: colors
      });
      confetti({
        particleCount: 3,
        angle: 120,
        spread: 55,
        origin: { x: 1 },
        colors: colors
      });

      if (Date.now() < end) {
        requestAnimationFrame(frame);
      }
    }());
  };

  const handleOptionSelect = (index: number) => {
    if (showResult) return;
    setSelectedOption(index);
    setShowResult(true);
    if (index === currentQuestion.correctAnswerIndex) {
      setScore(s => s + 1);
    }
  };

  const handleNext = () => {
    if (currentIndex < questions.length - 1) {
      setCurrentIndex(prev => prev + 1);
      setSelectedOption(null);
      setShowResult(false);
    } else {
      const finalScore = score + (selectedOption === currentQuestion.correctAnswerIndex ? 0 : 0);
      const percentage = (score / questions.length) * 100;
      
      // Calculate points earned
      let pointsEarned = score * 10; // 10 points per correct answer
      if (percentage === 100) pointsEarned += 50; // Bonus for full marks
      
      setQuizCompleted(true);
      if (percentage >= 80) {
        triggerConfetti();
      }
      
      if (onComplete) {
        onComplete(score, pointsEarned);
      }
    }
  };

  const handleShareQuizContent = async () => {
     // Format quiz into text
     let text = "🧠 SJ Tutor AI Quiz Challenge 🧠\n\n";
     questions.forEach((q, i) => {
         text += `Q${i+1}: ${q.question}\n`;
         q.options.forEach((opt, j) => {
             text += `   ${String.fromCharCode(65+j)}) ${opt}\n`;
         });
         text += "\n";
     });
     text += "\nCan you beat my score? Generated by SJ Tutor AI.";

    if (navigator.share) {
        try {
            await navigator.share({
                title: 'SJ Tutor AI Quiz Challenge',
                text: text
            });
        } catch (e) { console.log('Share canceled'); }
    } else {
        try {
            await navigator.clipboard.writeText(text);
            alert('Quiz questions copied to clipboard!');
        } catch (e) { alert('Failed to copy'); }
    }
  };

  const handleShare = async (platform: string) => {
    try {
      // 1. Save to backend to get a unique public ID
      const response = await fetch('/api/auth/share', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'QUIZ',
          title: 'Quiz Challenge',
          subtitle: `I scored ${score}/${questions.length} on this quiz!`,
          content: questions
        })
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.message || 'Sharing failed');

      const shareId = data.id;
      const shareUrl = `${window.location.origin}?share=${shareId}`;
      const text = `I scored ${score}/${questions.length} on my SJ Tutor AI Quiz! 🎓`;
      const shareTextWithLink = `${text}\nCheck it out here: ${shareUrl}`;
      
      let url = '';
      switch(platform) {
        case 'whatsapp':
          url = `https://wa.me/?text=${encodeURIComponent(shareTextWithLink)}`;
          break;
        case 'facebook':
          url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(text)}`;
          break;
        case 'telegram':
            url = `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(text)}`;
            break;
        case 'gmail':
             url = `https://mail.google.com/mail/u/0/?view=cm&fs=1&su=${encodeURIComponent("My SJ Tutor AI Score")}&body=${encodeURIComponent(shareTextWithLink)}`;
             break;
        case 'email':
          url = `mailto:?subject=My SJ Tutor AI Score&body=${encodeURIComponent(shareTextWithLink)}`;
          break;
        case 'instagram':
            navigator.clipboard.writeText(shareTextWithLink);
            alert("Score and link copied! Open Instagram to paste and share.");
            url = 'https://instagram.com';
            break;
        case 'copy':
            if (navigator.share) {
              try {
                await navigator.share({
                  title: 'My SJ Tutor AI Score',
                  text: text,
                  url: shareUrl,
                });
                return;
              } catch (err) {}
            }
            navigator.clipboard.writeText(shareUrl);
            alert("Share link copied to clipboard!");
            return;
      }
      
      if (url) window.open(url, '_blank');
    } catch (err: any) {
      console.error(err);
      alert('Sharing failed: ' + err.message);
    }
  };

  if (quizCompleted) {
    const percentage = Math.round((score / questions.length) * 100);
    let message = "Good effort, keep learning!";
    let icon = "📚";
    let colorClass = "from-blue-500 to-indigo-600";

    if (percentage >= 90) {
      message = "Unbelievable! You are a Genius! 🌟";
      icon = "🏆";
      colorClass = "from-amber-400 to-orange-500";
    } else if (percentage >= 80) {
      message = "Fantastic performance! So close! 🎯";
      icon = "⭐";
      colorClass = "from-emerald-400 to-teal-500";
    } else if (percentage >= 50) {
      message = "Great job! You're on the right track! 👍";
      icon = "✨";
    }

    const pointsEarned = score * 10 + (percentage === 100 ? 50 : 0);

    return (
      <div className="space-y-6">
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/80 backdrop-blur-sm">
          <motion.div 
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="bg-white dark:bg-slate-800 w-full max-w-lg rounded-3xl overflow-hidden shadow-2xl"
          >
            {/* Top Banner */}
            <div className={`bg-gradient-to-r ${colorClass} p-8 text-center text-white relative`}>
              <div className="absolute top-4 right-4 bg-white/20 p-2 rounded-full backdrop-blur-md">
                <Trophy size={20} />
              </div>
              <div className="text-6xl mb-4">{icon}</div>
              <h2 className="text-3xl font-black italic tracking-tighter">SUCCESS!</h2>
              <p className="text-white/80 font-medium">Quiz Completed Successfully</p>
            </div>

            <div className="p-8 text-center">
              <h3 className="text-xl font-bold dark:text-white mb-2">{message}</h3>
              
              <div className="flex justify-center items-end gap-1 mb-8">
                <span className="text-5xl font-black text-slate-900 dark:text-white">{score}</span>
                <span className="text-2xl text-slate-400 mb-1">/ {questions.length}</span>
              </div>

              {/* Rewards Section */}
              <div className="bg-slate-50 dark:bg-slate-900/50 rounded-2xl p-6 mb-8 border border-slate-100 dark:border-slate-700">
                 <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-3">Rewards Earned</p>
                 <div className="flex justify-center gap-4">
                    <div className="flex items-center gap-2 px-4 py-2 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 rounded-xl">
                      <Coins size={20} />
                      <span className="font-black text-lg">+{pointsEarned} <span className="text-xs font-medium opacity-70">PTS</span></span>
                    </div>
                    {percentage >= 80 && (
                      <div className="flex items-center gap-2 px-4 py-2 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 rounded-xl">
                        <Award size={20} />
                        <span className="font-black text-lg">+1 <span className="text-xs font-medium opacity-70">BADGE</span></span>
                      </div>
                    )}
                 </div>
              </div>

              <div className="grid grid-cols-2 gap-3 mb-6">
                <button
                  onClick={onReset}
                  className="flex items-center justify-center gap-2 py-4 bg-slate-900 dark:bg-white text-white dark:text-slate-900 rounded-2xl font-bold transition-transform active:scale-95"
                >
                  <RefreshCw size={18} />
                  Retry
                </button>
                <button
                  onClick={() => {
                     // Generic "Next Quiz" or Dashboard
                     onReset();
                  }}
                  className="flex items-center justify-center gap-2 py-4 bg-amber-500 text-white rounded-2xl font-bold transition-transform active:scale-95 shadow-lg shadow-amber-500/25"
                >
                  Next Quiz
                  <ArrowRight size={18} />
                </button>
              </div>

              <button
                 onClick={handleShareQuizContent}
                 className="flex items-center justify-center gap-2 w-full py-4 border-2 border-slate-100 dark:border-slate-700 text-slate-600 dark:text-slate-400 rounded-2xl font-bold hover:bg-slate-50 dark:hover:bg-slate-900/50 transition-all"
              >
                 <Share2 size={18} />
                 Share Result with Friends
              </button>
            </div>
          </motion.div>
        </div>

        <div className="bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden animate-in slide-in-from-bottom-4 duration-500 delay-150">
            <div className="px-6 py-4 bg-slate-50 border-b border-slate-200">
                <h3 className="font-bold text-slate-800 flex items-center gap-2">
                    <CheckCircle className="w-5 h-5 text-emerald-500" />
                    Correct Answers & Explanations
                </h3>
            </div>
            <div className="divide-y divide-slate-100">
                {questions.map((q, idx) => (
                    <div key={idx} className="p-6">
                        <p className="font-semibold text-slate-800 mb-4 flex gap-2">
                            <span className="text-slate-400 font-mono">{idx + 1}.</span>
                            {q.question}
                        </p>
                        <div className="space-y-2 pl-6 mb-4">
                            {q.options.map((opt, optIdx) => (
                                <div 
                                    key={optIdx} 
                                    className={`px-4 py-3 rounded-lg border text-sm flex justify-between items-center ${
                                        optIdx === q.correctAnswerIndex 
                                        ? 'bg-emerald-50 border-emerald-200 text-emerald-800 font-medium' 
                                        : 'bg-white border-slate-100 text-slate-500 opacity-75'
                                    }`}
                                >
                                    <span>{opt}</span>
                                    {optIdx === q.correctAnswerIndex && <CheckCircle className="w-4 h-4 text-emerald-500" />}
                                </div>
                            ))}
                        </div>
                        <div className="ml-6 p-4 bg-slate-50 rounded-lg text-sm text-slate-600 border border-slate-100">
                            <span className="font-bold text-slate-700">Explanation: </span>
                            {q.explanation}
                        </div>
                    </div>
                ))}
            </div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden">
      {/* Progress Bar */}
      <div className="w-full bg-slate-100 h-1.5">
        <div 
          className="bg-primary-600 h-1.5 transition-all duration-300"
          style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }}
        ></div>
      </div>

      <div className="p-6">
        <div className="flex justify-between items-center mb-6">
          <span className="text-xs font-bold text-primary-600 uppercase tracking-wider bg-primary-50 px-2 py-1 rounded">
            Question {currentIndex + 1} of {questions.length}
          </span>
          <span className="text-sm font-medium text-slate-500">Score: {score}</span>
        </div>

        <h3 className="text-xl font-semibold text-slate-800 mb-6">
          {currentQuestion.question}
        </h3>

        <div className="space-y-3">
          {currentQuestion.options.map((option, idx) => {
            let optionClass = "border-slate-200 hover:border-primary-300 hover:bg-slate-50";
            let icon = null;

            if (showResult) {
              if (idx === currentQuestion.correctAnswerIndex) {
                optionClass = "border-emerald-500 bg-emerald-50 text-emerald-800 ring-1 ring-emerald-500";
                icon = <CheckCircle className="w-5 h-5 text-emerald-600" />;
              } else if (idx === selectedOption) {
                optionClass = "border-rose-500 bg-rose-50 text-rose-800 ring-1 ring-rose-500";
                icon = <XCircle className="w-5 h-5 text-rose-600" />;
              } else {
                optionClass = "border-slate-100 opacity-50";
              }
            } else if (selectedOption === idx) {
               optionClass = "border-primary-500 bg-primary-50 ring-1 ring-primary-500";
            }

            return (
              <button
                key={idx}
                onClick={() => handleOptionSelect(idx)}
                disabled={showResult}
                className={`w-full text-left p-4 rounded-lg border-2 transition-all flex justify-between items-center ${optionClass}`}
              >
                <span className="font-medium">{option}</span>
                {icon}
              </button>
            );
          })}
        </div>

        {showResult && (
          <div className="mt-6 animate-in fade-in slide-in-from-top-2">
            <div className="bg-slate-50 p-4 rounded-lg border border-slate-200 mb-6">
              <span className="block text-xs font-bold text-slate-500 uppercase mb-1">Explanation</span>
              <p className="text-slate-700">{currentQuestion.explanation}</p>
            </div>
            <div className="flex justify-end">
              <button
                onClick={handleNext}
                className="inline-flex items-center px-6 py-2.5 bg-primary-600 hover:bg-primary-700 text-white rounded-lg font-medium transition-colors shadow-lg shadow-primary-500/20"
              >
                {currentIndex === questions.length - 1 ? 'Finish Quiz' : 'Next Question'}
                <ArrowRight className="w-4 h-4 ml-2" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default QuizView;
