
import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { Loader2, Volume2, Square, ArrowLeft, Download, FileText, Image as ImageIcon, FileType, Share2 } from 'lucide-react';
// @ts-ignore
import html2canvas from 'html2canvas';
// @ts-ignore
import { jsPDF } from 'jspdf';

interface ResultsViewProps {
  content: string;
  isLoading: boolean;
  title: string;
  type?: string; // 'Summary' | 'Essay' | 'Quiz' etc.
  onBack: () => void;
}

const ResultsView: React.FC<ResultsViewProps> = ({ content, isLoading, title, type = 'Document', onBack }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Cleanup speech when component unmounts
    return () => {
      window.speechSynthesis.cancel();
    };
  }, []);

  // Stop playing if content changes or loading starts
  useEffect(() => {
    if (isLoading) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    }
  }, [isLoading, content]);

  const toggleSpeech = () => {
    if (isPlaying) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    } else {
      if (!content) return;

      // Simple cleanup to remove markdown symbols for better reading
      const textToRead = content
        .replace(/[*#_`]/g, '') // Remove standard markdown chars
        .replace(/\[(.*?)\]\(.*?\)/g, '$1') // Keep link text, remove URL
        .replace(/\n/g, '. '); // Pause on newlines

      const utterance = new SpeechSynthesisUtterance(textToRead);
      utterance.rate = 1;
      utterance.pitch = 1;
      
      utterance.onend = () => setIsPlaying(false);
      utterance.onerror = () => setIsPlaying(false);
      
      window.speechSynthesis.speak(utterance);
      setIsPlaying(true);
    }
  };

  const getFilename = (ext: string) => {
    const cleanTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const cleanType = type.toLowerCase();
    return `${cleanTitle}_${cleanType}.${ext}`;
  };

  const handleShare = async () => {
    const textToShare = `${title} (${type})\n\n${content}\n\nGenerated by SJ Tutor AI`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: `SJ Tutor AI: ${title}`,
          text: textToShare,
        });
      } catch (err) {
        console.log('Share canceled');
      }
    } else {
      try {
        await navigator.clipboard.writeText(textToShare);
        alert('Content copied to clipboard!');
      } catch (err) {
        alert('Failed to copy content.');
      }
    }
  };

  const downloadText = () => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getFilename('txt');
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadWord = () => {
    if (!contentRef.current) return;
    
    // Create a structured HTML document for Word
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${title}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; }
          h1 { color: #2d3748; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; }
          .type-label { color: #B7950B; font-weight: bold; text-transform: uppercase; font-size: 12px; margin-bottom: 20px; }
          p { margin-bottom: 15px; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class='type-label'>${type}</div>
        ${contentRef.current.innerHTML}
      </body>
      </html>
    `;
    
    const blob = new Blob([htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getFilename('doc');
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadImage = async () => {
    if (!contentRef.current) return;
    setIsDownloading(true);
    try {
      const element = contentRef.current;
      const clone = element.cloneNode(true) as HTMLElement;
      
      clone.style.position = 'absolute';
      clone.style.left = '-9999px';
      clone.style.top = '0';
      clone.style.width = '800px';
      clone.style.height = 'auto';
      clone.style.padding = '50px';
      clone.style.background = 'white';
      
      // Add visual header to image
      const header = document.createElement('div');
      header.innerHTML = `
        <div style="margin-bottom: 30px; border-bottom: 2px solid #D4AF37; padding-bottom: 15px;">
          <h1 style="margin: 0; color: #1a202c; font-size: 28px; font-family: sans-serif;">${title}</h1>
          <p style="margin: 5px 0 0; color: #B7950B; font-weight: bold; text-transform: uppercase; font-size: 14px; font-family: sans-serif;">${type}</p>
        </div>
      `;
      clone.insertBefore(header, clone.firstChild);
      
      document.body.appendChild(clone);
      const canvas = await html2canvas(clone, { scale: 2, useCORS: true });
      document.body.removeChild(clone);

      const image = canvas.toDataURL('image/png');
      const a = document.createElement('a');
      a.href = image;
      a.download = getFilename('png');
      a.click();
    } catch (e) {
      console.error("Image download failed", e);
      alert("Failed to generate image.");
    } finally {
      setIsDownloading(false);
    }
  };

  const downloadPDF = async () => {
    if (!contentRef.current) return;
    setIsDownloading(true);
    try {
      const element = contentRef.current;
      const clone = element.cloneNode(true) as HTMLElement;
      
      const a4WidthPx = 750;

      clone.style.position = 'absolute';
      clone.style.left = '-9999px';
      clone.style.top = '0';
      clone.style.width = `${a4WidthPx}px`; 
      clone.style.height = 'auto'; 
      clone.style.overflow = 'visible';
      clone.style.maxHeight = 'none';
      clone.style.background = 'white';
      clone.style.color = 'black';
      clone.style.padding = '50px';
      
      // Add professional header to PDF clone
      const header = document.createElement('div');
      header.innerHTML = `
        <div style="margin-bottom: 30px; border-bottom: 2px solid #D4AF37; padding-bottom: 15px; font-family: sans-serif;">
          <h1 style="margin: 0; color: #1a202c; font-size: 26px;">${title}</h1>
          <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 8px;">
            <span style="color: #B7950B; font-weight: bold; text-transform: uppercase; font-size: 12px;">${type}</span>
            <span style="color: #718096; font-size: 12px;">Date: ${new Date().toLocaleDateString()}</span>
          </div>
        </div>
      `;
      clone.insertBefore(header, clone.firstChild);
      
      document.body.appendChild(clone);

      const canvas = await html2canvas(clone, { 
        scale: 2,
        useCORS: true,
        logging: false,
        windowWidth: a4WidthPx + 100
      });
      
      document.body.removeChild(clone);

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = pdf.internal.pageSize.getHeight();
      
      const imgProps = pdf.getImageProperties(imgData);
      const imgHeight = (imgProps.height * pdfWidth) / imgProps.width;
      
      let heightLeft = imgHeight;
      let position = 0;

      // First page
      pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
      heightLeft -= pdfHeight;

      // Subsequent pages (crucial for long essays)
      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, pdfWidth, imgHeight);
        heightLeft -= pdfHeight;
      }

      pdf.save(getFilename('pdf'));
    } catch (e) {
      console.error("PDF download failed", e);
      alert("Failed to generate PDF. Try downloading as Text or Word.");
    } finally {
      setIsDownloading(false);
    }
  };

  if (!content && !isLoading) return null;

  return (
    <div className="bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex justify-between items-center flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <button 
            onClick={onBack}
            className="p-2 -ml-2 text-slate-400 hover:text-primary-600 hover:bg-slate-100 rounded-lg transition-colors"
            title="Back"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex flex-col">
             <h3 className="font-semibold text-slate-800 line-clamp-1">{title}</h3>
             <span className="text-xs text-slate-500 font-medium">{type}</span>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          {!isLoading && content && (
            <>
              {/* Share & Download Options */}
              <div className="flex items-center bg-white border border-slate-200 rounded-lg p-1 mr-2 shadow-sm">
                 <button 
                   onClick={handleShare}
                   className="p-1.5 text-slate-500 hover:text-green-600 hover:bg-green-50 rounded-md transition-colors"
                   title="Share Content"
                 >
                   <Share2 className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={downloadPDF} 
                   disabled={isDownloading}
                   className="p-1.5 text-slate-500 hover:text-red-600 hover:bg-red-50 rounded-md transition-colors disabled:opacity-50"
                   title={`Download ${type} as PDF`}
                 >
                   <FileType className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={downloadWord} 
                   className="p-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-colors"
                   title={`Download ${type} as Word`}
                 >
                   <FileText className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={downloadImage} 
                   disabled={isDownloading}
                   className="p-1.5 text-slate-500 hover:text-purple-600 hover:bg-purple-50 rounded-md transition-colors disabled:opacity-50"
                   title={`Download ${type} as Image`}
                 >
                   <ImageIcon className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={downloadText} 
                   className="p-1.5 text-slate-500 hover:text-slate-800 hover:bg-slate-100 rounded-md transition-colors"
                   title={`Download ${type} as Text`}
                 >
                   <Download className="w-4 h-4" />
                 </button>
              </div>

              <button
                onClick={toggleSpeech}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                  isPlaying 
                    ? 'bg-red-50 text-red-600 hover:bg-red-100 border border-red-200' 
                    : 'bg-primary-50 text-primary-600 hover:bg-primary-100 border border-primary-200'
                }`}
                title={isPlaying ? "Stop reading" : "Read aloud"}
              >
                {isPlaying ? (
                  <>
                    <Square className="w-3.5 h-3.5 fill-current" />
                    <span className="hidden sm:inline">Stop</span>
                  </>
                ) : (
                  <>
                    <Volume2 className="w-4 h-4" />
                    <span className="hidden sm:inline">Listen</span>
                  </>
                )}
              </button>
            </>
          )}
        </div>

        {isLoading && (
          <div className="flex items-center text-primary-600 text-sm font-medium">
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Generating {type}...
          </div>
        )}
      </div>
      
      <div className="p-6 min-h-[200px]" ref={contentRef}>
        <div className="markdown-body text-slate-700 bg-white">
          <ReactMarkdown>{content}</ReactMarkdown>
        </div>
        {content === '' && isLoading && (
          <div className="flex flex-col items-center justify-center py-12 text-slate-400">
            <Loader2 className="w-8 h-8 mb-4 animate-spin text-primary-300" />
            <p>Initializing {type.toLowerCase()} generator...</p>
          </div>
        )}
      </div>
      
      {!isLoading && (
        <div className="p-4 bg-slate-50 border-t border-slate-100 flex justify-center">
            <button 
                onClick={onBack}
                className="text-sm font-semibold text-primary-700 hover:text-primary-800 hover:underline flex items-center gap-2"
            >
                <RefreshCw className="w-3.5 h-3.5" />
                Generate Another Version
            </button>
        </div>
      )}
    </div>
  );
};

// Simple Refresh icon helper
const RefreshCw = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"></path><path d="M21 3v5h-5"></path><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"></path><path d="M8 16H3v5"></path></svg>
);

export default ResultsView;
