
import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { Loader2, Volume2, Square, ArrowLeft, Download, FileText, Image as ImageIcon, FileType, Share2, Facebook, Instagram, Mail, Send, MessageCircle, Link, Globe } from 'lucide-react';
// @ts-ignore
import html2canvas from 'html2canvas';
// @ts-ignore
import { jsPDF } from 'jspdf';
import { db } from '../firebaseConfig';
import { collection, addDoc } from 'firebase/firestore';

interface ResultsViewProps {
  content: string;
  isLoading: boolean;
  title: string;
  type?: string; // 'Summary' | 'Essay' | 'Quiz' etc.
  onBack: () => void;
}

const ResultsView: React.FC<ResultsViewProps> = ({ content, isLoading, title, type = 'Document', onBack }) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [generatedLink, setGeneratedLink] = useState<string | null>(null);
  const [isGeneratingLink, setIsGeneratingLink] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    return () => {
      window.speechSynthesis.cancel();
    };
  }, []);

  useEffect(() => {
    if (isLoading) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    }
  }, [isLoading, content]);

  const toggleSpeech = () => {
    if (isPlaying) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    } else {
      if (!content) return;

      const textToRead = content
        .replace(/[*#_`]/g, '') 
        .replace(/\[(.*?)\]\(.*?\)/g, '$1') 
        .replace(/\n/g, '. '); 

      const utterance = new SpeechSynthesisUtterance(textToRead);
      utterance.rate = 1;
      utterance.pitch = 1;
      
      utterance.onend = () => setIsPlaying(false);
      utterance.onerror = () => setIsPlaying(false);
      
      window.speechSynthesis.speak(utterance);
      setIsPlaying(true);
    }
  };

  const getFilename = (ext: string) => {
    const cleanTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const cleanType = type.toLowerCase();
    return `${cleanTitle}_${cleanType}.${ext}`;
  };

  const handleGeneratePublicLink = async () => {
    if (generatedLink) {
        navigator.clipboard.writeText(generatedLink);
        alert("Link copied!");
        return;
    }
    
    setIsGeneratingLink(true);
    try {
        const docRef = await addDoc(collection(db, "shared_content"), {
            title: title,
            type: type,
            content: content,
            createdAt: new Date()
        });
        
        const url = `${window.location.origin}/?shareId=${docRef.id}`;
        setGeneratedLink(url);
        navigator.clipboard.writeText(url);
        alert("Public link generated and copied to clipboard!");
    } catch (e) {
        console.error("Error creating share link", e);
        alert("Failed to generate link. Please try again.");
    } finally {
        setIsGeneratingLink(false);
    }
  };

  const handleShare = async (platform?: string) => {
    const textToShare = `${title} (${type})\n\nGenerated by SJ Tutor AI`;
    const appUrl = generatedLink || window.location.href;
    const shareTextWithLink = `${textToShare}\nCheck it out here: ${appUrl}`;
    
    if (!platform) {
        if (navigator.share) {
            try {
              await navigator.share({
                title: `SJ Tutor AI: ${title}`,
                text: textToShare,
                url: appUrl
              });
            } catch (err) {}
        } else {
            try {
              await navigator.clipboard.writeText(shareTextWithLink);
              alert('Link copied to clipboard!');
            } catch (err) {
              alert('Failed to copy content.');
            }
        }
        return;
    }

    let shareUrl = '';
    switch(platform) {
      case 'whatsapp':
        shareUrl = `https://wa.me/?text=${encodeURIComponent(shareTextWithLink)}`;
        break;
      case 'facebook':
        shareUrl = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(appUrl)}&quote=${encodeURIComponent(textToShare)}`;
        break;
      case 'telegram':
          shareUrl = `https://t.me/share/url?url=${encodeURIComponent(appUrl)}&text=${encodeURIComponent(textToShare)}`;
          break;
      case 'gmail':
           shareUrl = `https://mail.google.com/mail/u/0/?view=cm&fs=1&su=${encodeURIComponent("SJ Tutor AI: " + title)}&body=${encodeURIComponent(shareTextWithLink)}`;
           break;
      case 'copy':
          navigator.clipboard.writeText(appUrl);
          alert("Link copied!");
          return;
    }
    
    if (shareUrl) window.open(shareUrl, '_blank');
  };

  const downloadText = () => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getFilename('txt');
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadWord = () => {
    if (!contentRef.current) return;
    
    const htmlContent = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head>
        <meta charset='utf-8'>
        <title>${title}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; }
          h1 { color: #2d3748; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; }
          .type-label { color: #B7950B; font-weight: bold; text-transform: uppercase; font-size: 12px; margin-bottom: 20px; }
          p { margin-bottom: 15px; }
          img { max-width: 100%; height: auto; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <div class='type-label'>${type}</div>
        ${contentRef.current.innerHTML}
      </body>
      </html>
    `;
    
    const blob = new Blob([htmlContent], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = getFilename('doc');
    a.click();
    URL.revokeObjectURL(url);
  };

  const downloadImage = async () => {
    if (!contentRef.current) return;
    setIsDownloading(true);
    try {
      const element = contentRef.current;
      const clone = element.cloneNode(true) as HTMLElement;
      
      clone.style.position = 'absolute';
      clone.style.left = '-9999px';
      clone.style.top = '0';
      clone.style.width = '800px';
      clone.style.height = 'auto';
      clone.style.padding = '50px';
      clone.style.background = 'white';
      
      const header = document.createElement('div');
      header.innerHTML = `
        <div style="margin-bottom: 30px; border-bottom: 2px solid #D4AF37; padding-bottom: 15px;">
          <h1 style="margin: 0; color: #1a202c; font-size: 28px; font-family: sans-serif;">${title}</h1>
          <p style="margin: 5px 0 0; color: #B7950B; font-weight: bold; text-transform: uppercase; font-size: 14px; font-family: sans-serif;">${type}</p>
        </div>
      `;
      clone.insertBefore(header, clone.firstChild);
      
      document.body.appendChild(clone);
      const canvas = await html2canvas(clone, { scale: 2, useCORS: true, allowTaint: true });
      document.body.removeChild(clone);

      const image = canvas.toDataURL('image/png');
      const a = document.createElement('a');
      a.href = image;
      a.download = getFilename('png');
      a.click();
    } catch (e) {
      console.error("Image download failed", e);
      alert("Failed to generate image.");
    } finally {
      setIsDownloading(false);
    }
  };

  const handlePrintPDF = () => {
    window.print();
  };

  if (!content && !isLoading) return null;

  return (
    <div className="bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500 print:shadow-none print:border-none">
      <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex justify-between items-center flex-wrap gap-4 print:hidden">
        <div className="flex items-center gap-3">
          <button 
            onClick={onBack}
            className="p-2 -ml-2 text-slate-400 hover:text-primary-600 hover:bg-slate-100 rounded-lg transition-colors"
            title="Back"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex flex-col">
             <h3 className="font-semibold text-slate-800 line-clamp-1">{title}</h3>
             <span className="text-xs text-slate-500 font-medium">{type}</span>
          </div>
        </div>
        
        <div className="flex items-center gap-2">
          {!isLoading && content && (
            <>
              <div className="flex items-center bg-white border border-slate-200 rounded-lg p-1 mr-2 shadow-sm">
                 <button 
                   onClick={() => handleShare()}
                   className="p-1.5 text-slate-500 hover:text-green-600 hover:bg-green-50 rounded-md transition-colors"
                   title="Share Content"
                 >
                   <Share2 className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={handlePrintPDF} 
                   className="p-1.5 text-slate-500 hover:text-red-600 hover:bg-red-50 rounded-md transition-colors disabled:opacity-50"
                   title={`Print / Save as PDF`}
                 >
                   <FileType className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={downloadWord} 
                   className="p-1.5 text-slate-500 hover:text-blue-600 hover:bg-blue-50 rounded-md transition-colors"
                   title={`Download ${type} as Word`}
                 >
                   <FileText className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={downloadImage} 
                   disabled={isDownloading}
                   className="p-1.5 text-slate-500 hover:text-purple-600 hover:bg-purple-50 rounded-md transition-colors disabled:opacity-50"
                   title={`Download ${type} as Image`}
                 >
                   <ImageIcon className="w-4 h-4" />
                 </button>
                 <div className="w-px h-4 bg-slate-200 mx-1"></div>
                 <button 
                   onClick={downloadText} 
                   className="p-1.5 text-slate-500 hover:text-slate-800 hover:bg-slate-100 rounded-md transition-colors"
                   title={`Download ${type} as Text`}
                 >
                   <Download className="w-4 h-4" />
                 </button>
              </div>

              <button
                onClick={handleGeneratePublicLink}
                disabled={isGeneratingLink}
                className="flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium transition-colors bg-blue-50 text-blue-600 hover:bg-blue-100 border border-blue-200"
                title="Create a shareable public link"
              >
                 {isGeneratingLink ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Globe className="w-3.5 h-3.5" />}
                 <span className="hidden sm:inline">Public Link</span>
              </button>

              <button
                onClick={toggleSpeech}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                  isPlaying 
                    ? 'bg-red-50 text-red-600 hover:bg-red-100 border border-red-200' 
                    : 'bg-primary-50 text-primary-600 hover:bg-primary-100 border border-primary-200'
                }`}
                title={isPlaying ? "Stop reading" : "Read aloud"}
              >
                {isPlaying ? (
                  <>
                    <Square className="w-3.5 h-3.5 fill-current" />
                    <span className="hidden sm:inline">Stop</span>
                  </>
                ) : (
                  <>
                    <Volume2 className="w-4 h-4" />
                    <span className="hidden sm:inline">Listen</span>
                  </>
                )}
              </button>
            </>
          )}
        </div>

        {isLoading && (
          <div className="flex items-center text-primary-600 text-sm font-medium">
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Generating {type}...
          </div>
        )}
      </div>
      
      <div className="p-6 min-h-[200px] print:p-0 print:m-0" ref={contentRef}>
        {/* Print Only Header */}
        <div className="hidden print:block border-b-2 border-primary-500 mb-6 pb-2">
            <h1 className="text-3xl font-bold text-slate-900">{title}</h1>
            <p className="text-sm text-slate-500 uppercase font-bold mt-1">{type} • Generated by SJ Tutor AI</p>
        </div>

        <div className="markdown-body text-slate-700 bg-white">
          <ReactMarkdown
            components={{
                img: ({node, ...props}) => <img {...props} style={{maxWidth: '100%', height: 'auto', borderRadius: '8px', margin: '20px 0'}} />
            }}
          >
            {content}
          </ReactMarkdown>
        </div>
        {content === '' && isLoading && (
          <div className="flex flex-col items-center justify-center py-12 text-slate-400">
            <Loader2 className="w-8 h-8 mb-4 animate-spin text-primary-300" />
            <p>Initializing {type.toLowerCase()} generator...</p>
          </div>
        )}
      </div>
      
      {!isLoading && (
        <div className="p-6 bg-slate-50 border-t border-slate-100 print:hidden">
            <div className="flex flex-col items-center gap-4">
                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Share this {type}</p>
                <div className="flex flex-wrap justify-center gap-3">
                    <button onClick={() => handleShare('whatsapp')} className="p-2.5 bg-[#25D366] text-white rounded-full hover:scale-110 transition-transform shadow-sm" title="WhatsApp">
                        <MessageCircle className="w-4 h-4 fill-current" />
                    </button>
                    <button onClick={() => handleShare('facebook')} className="p-2.5 bg-[#1877F2] text-white rounded-full hover:scale-110 transition-transform shadow-sm" title="Facebook">
                        <Facebook className="w-4 h-4 fill-current" />
                    </button>
                    <button onClick={() => handleShare('telegram')} className="p-2.5 bg-[#0088cc] text-white rounded-full hover:scale-110 transition-transform shadow-sm" title="Telegram">
                        <Send className="w-4 h-4 fill-current" />
                    </button>
                    <button onClick={() => handleShare('gmail')} className="p-2.5 bg-[#EA4335] text-white rounded-full hover:scale-110 transition-transform shadow-sm" title="Gmail">
                        <Mail className="w-4 h-4 fill-current" />
                    </button>
                    <button onClick={() => handleShare('copy')} className="p-2.5 bg-slate-800 text-white rounded-full hover:scale-110 transition-transform shadow-sm" title="Copy Link">
                        <Link className="w-4 h-4" />
                    </button>
                </div>
                
                <button 
                    onClick={onBack}
                    className="mt-4 text-sm font-semibold text-primary-700 hover:text-primary-800 hover:underline flex items-center gap-2"
                >
                    <RefreshCw className="w-3.5 h-3.5" />
                    Generate Another Version
                </button>
            </div>
        </div>
      )}
    </div>
  );
};

const RefreshCw = ({ className }: { className?: string }) => (
  <svg className={className} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"></path><path d="M21 3v5h-5"></path><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"></path><path d="M8 16H3v5"></path></svg>
);

export default ResultsView;
