
import React, { useState, useEffect, useRef } from 'react';
import ReactMarkdown from 'react-markdown';
import { Loader2, Volume2, Square, ArrowLeft, Download, Share2, Facebook, Mail, MessageCircle, Link, RefreshCw, Check, Copy } from 'lucide-react';
import { createSharedContent } from '../utils/firebaseUtils';
// @ts-expect-error - html2canvas missing types
import html2canvas from 'html2canvas';
// @ts-expect-error - jspdf missing types
import { jsPDF } from 'jspdf';

interface ResultsViewProps {
  content: string;
  isLoading: boolean;
  title: string;
  type?: string; // 'Summary' | 'Essay' | 'Quiz' etc.
  onBack: () => void;
  isViewingShared?: boolean;
  onAddToMyList?: () => void;
  isAddedToList?: boolean;
  onSharePublicLink?: (type: string, title: string, content: any) => void;
}

const ResultsView: React.FC<ResultsViewProps> = ({ 
  content, 
  isLoading, 
  title, 
  type = 'Document', 
  onBack,
  isViewingShared = false,
  onAddToMyList,
  isAddedToList = false,
  onSharePublicLink
}) => {
  const [isPlaying, setIsPlaying] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    // Cleanup speech synthesis on unmount
    return () => {
      window.speechSynthesis.cancel();
    };
  }, []);

  useEffect(() => {
    if (isLoading) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    }
  }, [isLoading, content]);

  const toggleSpeech = () => {
    if (isPlaying) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    } else {
      if (!content) return;

      // Clean up text for better speech (remove some markdown symbols)
      const textToRead = content
        .replace(/[*#_`]/g, '') // Remove formatting characters
        .replace(/\[(.*?)\]\(.*?\)/g, '$1') // Keep link text, remove URL
        .replace(/\n/g, '. '); // Pause on newlines

      const utterance = new SpeechSynthesisUtterance(textToRead);
      utterance.rate = 1;
      utterance.pitch = 1;
      
      utterance.onend = () => setIsPlaying(false);
      utterance.onerror = () => setIsPlaying(false);
      
      window.speechSynthesis.speak(utterance);
      setIsPlaying(true);
    }
  };

  const getFilename = (ext: string) => {
    const cleanTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const cleanType = type.toLowerCase();
    return `${cleanTitle}_${cleanType}.${ext}`;
  };

  const handleShare = async (platform?: string) => {
    try {
      let shareUrl = window.location.origin;
      try {
        const shareId = await createSharedContent(
          type.toUpperCase(),
          title,
          content,
          "guest"
        );
        shareUrl = `${window.location.origin}/share/${shareId}`;
      } catch (backendError) {
        console.warn("Sharing to Firestore failed, using local share only", backendError);
      }

      const shareText = `${title} (${type})\n\n${content.substring(0, 300)}...\n\nRead more on SJ Tutor AI: ${shareUrl}`;
      const fullContent = `${title} (${type})\n\n${content}\n\nGenerated by SJ Tutor AI\n${shareUrl}`;

      if (!platform) {
          // Native Share or Copy
          if (navigator.share) {
              try {
                await navigator.share({
                  title: `SJ Tutor AI: ${title}`,
                  text: fullContent,
                  url: shareUrl,
                });
              } catch (err) {
                console.log("Share cancelled or failed", err);
              }
          } else {
              try {
                await navigator.clipboard.writeText(fullContent);
                alert('Share link copied to clipboard!');
              } catch {
                alert('Failed to copy content.');
              }
          }
          return;
      }

      let url = '';
      switch(platform) {
        case 'whatsapp':
          url = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
          break;
        case 'facebook':
          url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}&quote=${encodeURIComponent(shareText)}`;
          break;
        case 'gmail':
             url = `https://mail.google.com/mail/u/0/?view=cm&fs=1&su=${encodeURIComponent("SJ Tutor AI: " + title)}&body=${encodeURIComponent(fullContent)}`;
             break;
        case 'copy':
            try {
              await navigator.clipboard.writeText(shareUrl);
              alert("Share link copied to clipboard!");
            } catch {
              alert("Failed to copy.");
            }
            return;
      }
      
      if (url) window.open(url, '_blank');
    } catch (err: any) {
      console.error(err);
      alert('Sharing failed: ' + err.message);
    }
  };

  const downloadPDF = async () => {
    if (!contentRef.current) return;
    setIsDownloading(true);
    try {
      const element = contentRef.current;
      const clone = element.cloneNode(true) as HTMLElement;
      
      // A4 width in pixels at 96 DPI is approx 794px. We use 750 for content + margins.
      const a4WidthPx = 750;

      clone.style.position = 'absolute';
      clone.style.left = '-9999px';
      clone.style.top = '0';
      clone.style.width = `${a4WidthPx}px`; 
      clone.style.height = 'auto'; 
      clone.style.overflow = 'visible';
      clone.style.maxHeight = 'none';
      clone.style.background = 'white';
      clone.style.color = 'black'; // Force black text for PDF
      clone.style.padding = '40px';
      
      const header = document.createElement('div');
      header.innerHTML = `
        <div style="margin-bottom: 30px; border-bottom: 2px solid #D4AF37; padding-bottom: 15px; font-family: sans-serif;">
          <h1 style="margin: 0; color: #1a202c; font-size: 26px;">${title}</h1>
          <div style="display: flex; justify-content: space-between; align-items: center; margin-top: 8px;">
            <span style="color: #B7950B; font-weight: bold; text-transform: uppercase; font-size: 12px;">${type}</span>
            <span style="color: #718096; font-size: 12px;">SJ Tutor AI - Generated on ${new Date().toLocaleDateString()}</span>
          </div>
        </div>
      `;
      clone.insertBefore(header, clone.firstChild);
      
      document.body.appendChild(clone);

      const canvas = await html2canvas(clone, { 
        scale: 2, // High resolution
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        windowWidth: a4WidthPx + 100
      });
      
      document.body.removeChild(clone);

      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF('p', 'mm', 'a4');
      
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      
      const widthRatio = pageWidth / canvas.width;
      const canvasHeight = canvas.height * widthRatio;
      
      let heightLeft = canvasHeight;
      let position = 0;

      // Add first page
      pdf.addImage(imgData, 'PNG', 0, position, pageWidth, canvasHeight);
      heightLeft -= pageHeight;

      // Add subsequent pages if content overflows
      while (heightLeft > 0) {
        position -= pageHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, pageWidth, canvasHeight);
        heightLeft -= pageHeight;
      }

      pdf.save(getFilename('pdf'));
    } catch (e) {
      console.error("PDF download failed", e);
      alert("Failed to generate PDF. Try downloading as Text or Word.");
    } finally {
      setIsDownloading(false);
    }
  };

  const downloadMarkdown = () => {
    try {
      const heading = `# ${title}\nCategory: ${type}\nGenerated via SJ Tutor AI on ${new Date().toLocaleDateString()}\n\n---\n\n`;
      const fileContent = heading + content;
      const element = document.createElement("a");
      const file = new Blob([fileContent], { type: 'text/markdown;charset=utf-8' });
      element.href = URL.createObjectURL(file);
      element.download = getFilename('md');
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    } catch (e) {
      console.error("Markdown download failed", e);
      alert("Failed to download Markdown file.");
    }
  };

  const downloadWord = () => {
    try {
      const formattedContent = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
          <head>
            <title>${title}</title>
            <style>
              body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; }
              h1 { color: #1a202c; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; font-size: 24px; }
              h2 { color: #2d3748; margin-top: 20px; font-size: 18px; }
              p, li { color: #333333; font-size: 14px; }
              hr { border: none; border-top: 1px solid #e2e8f0; margin: 20px 0; }
              .footer { font-size: 11px; color: #718096; margin-top: 30px; text-align: center; }
            </style>
          </head>
          <body>
            <h1>${title}</h1>
            <p><strong>Resource Type:</strong> ${type}</p>
            <p><strong>Generated on:</strong> ${new Date().toLocaleDateString()} by SJ Tutor AI</p>
            <hr />
            <div style="white-space: pre-wrap;">${content}</div>
            <hr />
            <p class="footer">Thank you for studying with SJ Tutor AI. Keep up the amazing streak!</p>
          </body>
        </html>
      `;
      const element = document.createElement("a");
      const file = new Blob(['\ufeff' + formattedContent], { type: 'application/msword;charset=utf-8' });
      element.href = URL.createObjectURL(file);
      element.download = getFilename('doc');
      document.body.appendChild(element);
      element.click();
      document.body.removeChild(element);
    } catch (e) {
      console.error("Word download failed", e);
      alert("Failed to download Word document.");
    }
  };

  if (!content && !isLoading) return null;

  return (
    <div className="bg-white rounded-xl shadow-md border border-slate-200 overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Header Toolbar */}
      <div className="bg-slate-50 px-4 sm:px-6 py-4 border-b border-slate-200 flex flex-col sm:flex-row justify-between items-center gap-4">
        <div className="flex items-center gap-3 w-full sm:w-auto">
          <button 
            onClick={onBack}
            className="p-2 -ml-2 text-slate-400 hover:text-primary-600 hover:bg-slate-100 rounded-lg transition-colors"
            title="Back to Form"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="flex flex-col overflow-hidden">
             <h3 className="font-semibold text-slate-800 truncate max-w-[200px] sm:max-w-xs">{title}</h3>
             <span className="text-xs text-slate-500 font-medium">{type}</span>
          </div>
        </div>
        
        <div className="flex flex-wrap justify-end gap-2.5 w-full sm:w-auto">
          {!isLoading && content && (
            <>
              {/* Specific Action Buttons per User Request */}
              <div className="flex flex-wrap items-center gap-2 bg-slate-50 p-1 rounded-xl border border-slate-205/80 shadow-sm">
                {/* Save Button */}
                <button
                  onClick={() => alert("🎉 Successfully saved! This document is persistently cataloged in your learning logs.")}
                  className="px-3 py-1.5 bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 rounded-lg text-xs font-bold transition flex items-center gap-1.5 shadow-xs"
                  title="Save content"
                >
                  <Check className="w-3.5 h-3.5 text-emerald-500" />
                  <span>Save</span>
                </button>

                {/* Download PDF Button */}
                <button
                  onClick={downloadPDF}
                  disabled={isDownloading}
                  className="px-3 py-1.5 bg-white hover:bg-red-50 hover:text-red-650 border border-slate-200 text-slate-700 rounded-lg text-xs font-bold transition flex items-center gap-1.5 disabled:opacity-50 shadow-xs"
                  title="Download as PDF"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download PDF</span>
                </button>

                {/* Download Word DOC Button */}
                <button
                  onClick={downloadWord}
                  className="px-3 py-1.5 bg-white hover:bg-blue-50 hover:text-blue-655 border border-slate-200 text-slate-700 rounded-lg text-xs font-bold transition flex items-center gap-1.5 shadow-xs"
                  title="Download as Word"
                >
                  <Download className="w-3.5 h-3.5 text-blue-500" />
                  <span>Word (.doc)</span>
                </button>

                {/* Download Markdown Button */}
                <button
                  onClick={downloadMarkdown}
                  className="px-3 py-1.5 bg-white hover:bg-indigo-50 hover:text-indigo-655 border border-slate-200 text-slate-700 rounded-lg text-xs font-bold transition flex items-center gap-1.5 shadow-xs"
                  title="Download as Markdown"
                >
                  <Download className="w-3.5 h-3.5 text-indigo-500" />
                  <span>Markdown (.md)</span>
                </button>

                {/* Copy Button */}
                <button
                  onClick={async () => {
                    try {
                      await navigator.clipboard.writeText(content);
                      alert("Successfully copied generated markdown text to clipboard!");
                    } catch {
                      alert("Failed to copy text.");
                    }
                  }}
                  className="px-3 py-1.5 bg-white hover:bg-slate-50 border border-slate-200 text-slate-700 rounded-lg text-xs font-bold transition flex items-center gap-1.5 shadow-xs"
                  title="Copy to Clipboard"
                >
                  <Copy className="w-3.5 h-3.5" />
                  <span>Copy</span>
                </button>

                {/* Share Public Link Button */}
                <button
                  onClick={() => onSharePublicLink && onSharePublicLink(type === 'Summary' ? 'summary' : 'homework', title, content)}
                  className="px-3 py-1.5 bg-gradient-to-r from-primary-500 to-primary-700 hover:brightness-110 text-white rounded-lg text-xs font-extrabold transition flex items-center gap-1.5 shadow-sm active:scale-95"
                  title="Generate Public Shareable Link"
                >
                  <Share2 className="w-3.5 h-3.5" />
                  <span>Share Public Link</span>
                </button>
              </div>

              {/* Listen Button */}
              <button
                onClick={toggleSpeech}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-sm font-medium transition-colors border shadow-sm ${
                  isPlaying 
                    ? 'bg-red-50 text-red-600 hover:bg-red-100 border-red-200' 
                    : 'bg-primary-50 text-primary-600 hover:bg-primary-100 border-primary-200'
                }`}
                title={isPlaying ? "Stop reading" : "Read aloud"}
              >
                {isPlaying ? (
                  <>
                    <Square className="w-3.5 h-3.5 fill-current" />
                    <span className="hidden sm:inline">Stop</span>
                  </>
                ) : (
                  <>
                    <Volume2 className="w-4 h-4" />
                    <span className="hidden sm:inline">Listen</span>
                  </>
                )}
              </button>
            </>
          )}
        </div>

        {isLoading && (
          <div className="flex items-center text-primary-600 text-sm font-medium animate-pulse">
            <Loader2 className="w-4 h-4 mr-2 animate-spin" />
            Generating {type}...
          </div>
        )}
      </div>
      
      {isViewingShared && onAddToMyList && (
        <div className="bg-primary-50 dark:bg-slate-800 border-y border-primary-100 dark:border-slate-700 px-6 py-4 flex flex-col sm:flex-row justify-between items-center gap-4 animate-in fade-in duration-300">
          <div className="flex items-center gap-3">
            <span role="img" aria-label="gift" className="text-xl">✨</span>
            <div className="text-left">
              <p className="text-sm font-semibold text-slate-800 dark:text-slate-100">Viewing Shared {type}</p>
              <p className="text-xs text-slate-500 dark:text-slate-400">This AI-generated {type.toLowerCase()} was shared with you. Save it to keep it forever on your dashboard!</p>
            </div>
          </div>
          <button
            onClick={onAddToMyList}
            disabled={isAddedToList}
            className={`w-full sm:w-auto px-5 py-2.5 text-xs font-bold rounded-xl shadow-md transition-all flex items-center justify-center gap-1.5 ${
              isAddedToList 
                ? 'bg-slate-200 text-slate-450 dark:bg-slate-700 dark:text-slate-400 cursor-not-allowed shadow-none' 
                : 'bg-primary-600 hover:bg-primary-700 text-white transform hover:-translate-y-0.5'
            }`}
          >
            {isAddedToList ? '✓ Added to Study History' : '📥 Add to My Study List'}
          </button>
        </div>
      )}

      {/* Content Area */}
      <div className="p-6 sm:p-8 min-h-[300px]" ref={contentRef}>
        <div className="markdown-body text-slate-700 bg-white">
          <ReactMarkdown>{content}</ReactMarkdown>
        </div>
        {content === '' && isLoading && (
          <div className="flex flex-col items-center justify-center py-20 text-slate-400">
            <Loader2 className="w-10 h-10 mb-4 animate-spin text-primary-300" />
            <p className="text-sm font-medium">Initializing {type.toLowerCase()} generator...</p>
          </div>
        )}
      </div>
      
      {/* Footer Share Section */}
      {!isLoading && (
        <div className="p-6 bg-slate-50 border-t border-slate-100">
            <div className="flex flex-col items-center gap-4">
                <p className="text-xs font-bold text-slate-400 uppercase tracking-widest">Share this {type}</p>
                <div className="flex flex-wrap justify-center gap-3">
                    <button 
                      onClick={() => handleShare('whatsapp')} 
                      className="flex items-center gap-2 px-4 py-2 bg-[#25D366] text-white rounded-full hover:brightness-110 transition-transform shadow-sm active:scale-95" 
                      title="Share on WhatsApp"
                    >
                        <MessageCircle className="w-4 h-4 fill-current" />
                        <span className="text-xs font-bold">WhatsApp</span>
                    </button>
                    <button 
                      onClick={() => handleShare('facebook')} 
                      className="flex items-center gap-2 px-4 py-2 bg-[#1877F2] text-white rounded-full hover:brightness-110 transition-transform shadow-sm active:scale-95" 
                      title="Share on Facebook"
                    >
                        <Facebook className="w-4 h-4 fill-current" />
                        <span className="text-xs font-bold">Facebook</span>
                    </button>
                    <button 
                      onClick={() => handleShare('gmail')} 
                      className="flex items-center gap-2 px-4 py-2 bg-[#EA4335] text-white rounded-full hover:brightness-110 transition-transform shadow-sm active:scale-95" 
                      title="Share via Gmail"
                    >
                        <Mail className="w-4 h-4 fill-current" />
                        <span className="text-xs font-bold">Gmail</span>
                    </button>
                    <button 
                      onClick={() => handleShare('copy')} 
                      className="flex items-center gap-2 px-4 py-2 bg-slate-800 text-white rounded-full hover:bg-slate-900 transition-transform shadow-sm active:scale-95" 
                      title="Copy to Clipboard"
                    >
                        <Link className="w-4 h-4" />
                        <span className="text-xs font-bold">Copy Link</span>
                    </button>
                </div>
                
                <button 
                    onClick={onBack}
                    className="mt-6 text-sm font-semibold text-primary-700 hover:text-primary-800 hover:underline flex items-center gap-2 group"
                >
                    <RefreshCw className="w-3.5 h-3.5 group-hover:rotate-180 transition-transform duration-500" />
                    Generate Another Version
                </button>
            </div>
        </div>
      )}
    </div>
  );
};

export default ResultsView;
